@startuml
skinparam classAttributeIconSize 0

class User{
    +id: string
    +username: string
    +password: string
    +email: string
    +phoneNumber: string
}

class Admin{
    +id: string
    +username: string
    +password: string
    +isAdmin: boolean
}

class Post {
    +id: int
    +title: string
    +content: string
    +date: date
    +author: User
}

class Comment {
    +id: int
    +content: string
    +date: date
    +author: User
    +post: Post
}

class Rally {
    +id: int
    +title: string
    +date: date
    +location: string
    +creator: User
}

package controller {
    class UserController {
        +addUser(userData)
        +getUser(userId)
        +putUser(userId, userData)
        +deleteUser(userId)
    }

    class PostController {
        +addPost(postData)
        +getPost(postId)
        +putPost(postId, postData)
        +deletePost(postId)
    }

    class CommentController {
        +addComment(commentData)
        +getComment(commentId)
        +putComment(commentId, commentData)
        +deleteComment(commentId)
    }

    class RallyController {
        +addRally(rallyData)
        +getRally(rallyId)
        +putRally(rallyId, rallyData)
        +deleteRally(rallyId)
    }

    class CourtController {
        +addCourt(courtData)
        +getCourt(courtId)
        +putCourt(courtId, courtData)
        +deleteCourt(courtId)
    }

    class AdminController {
        +addAdmin(adminData)
        +getAdmin(adminId)
        +putAdmin(adminId, adminData)
        +deleteAdmin(adminId)
    }
}

User "1" -- "*" Post: can post >
User "1" -- "*" Comment: can comment >
Post -[hidden]> User
User "1..*" -- "1" Rally: contains <
Post "1" -- "*" Comment: has >
Admin "1" -- "*" User: manage >
Admin "1" -- "*" Post: manage >

@enduml