@startuml
skinparam classAttributeIconSize 0

class User {
    +id: string
    +username: string
    +email: string
    +password: string
    +isAdmin: boolean
}

class Post {
    +id: int
    +title: string
    +content: string
    +date: date
    +author: User
}

class Comment {
    +id: int
    +content: string
    +date: date
    +author: User
    +post: Post
}

class Rally {
    +id: int
    +title: string
    +date: date
    +location: string
    +creator: User
}

class Courtmate {
    +id: int
    +name: string
    +contact: string
}

User "1" -- "many" Post
User "1" -- "many" Comment
User "1" -- "many" Rally
Post "1" -- "many" Comment
Rally "many" -- "many" Courtmate

@enduml
