@startuml
title Sequence Diagram of Comment

actor User

activate CommentInterface
activate CommentController

User -> CommentInterface: click "Comment"
CommentInterface -> CommentController: getPost()

activate PostController
CommentController -> PostController: getPost()
PostController -> CommentController: providePost()
deactivate PostController

CommentController -> CommentInterface: showPost()

User -> CommentInterface: addComment()
CommentInterface -> CommentController: addComment()
CommentController -> CommentInterface: displaySuccessMessage()

deactivate CommentInterface
deactivate CommentController

@enduml
