@startuml
title Sequence Diagram of Post info

actor User
activate PostInterface
activate PostController

User -> PostInterface: click "Add New Post"
PostInterface -> PostController : getCategories()
PostController -> PostInterface : provideCategories()

alt Post about Badminton-Related Info

    User -> PostInterface : addPost()
    PostInterface -> PostController : addPost()
    PostController -> PostInterface : displaySuccessMessage()

else Post about Find a Courtmate

    User -> PostInterface : createRally()
    PostInterface -> PostController : createRally()

    activate RallyController
    PostController -> RallyController : createRally()
    RallyController -> PostController : showForm()
    PostController -> PostInterface : showForm()
    User -> PostInterface : submitForm()
    PostInterface -> PostController : submitForm()
    PostController -> RallyController : submitForm()

    alt Form is not valid

        RallyController -> PostController : displayErrorMessage()
        PostController -> PostInterface : displayErrorMessage()
        RallyController -> PostController : showForm()
        PostController -> PostInterface : showForm()

    else Form is valid

        RallyController -> PostController : displaySuccessMessage()
        PostController -> PostInterface : displaySuccessMessage()
        deactivate RallyController

        User -> PostInterface : addPost()
        PostInterface -> PostController : addPost()
        PostController -> PostInterface : displaySuccessMessage()
        User -[hidden]> PostController

    end

else Post about Sport Equipment

    User -> PostInterface : addPost()
    PostInterface -> PostController : addPost()
    PostController -> PostInterface : displaySuccessMessage()
        User -[hidden]> PostController

end

deactivate PostInterface
deactivate PostController

@enduml
