@startuml
title Sequence Diagram of View Info

actor User
activate PostInterface
activate PostController

User -> PostInterface : click "View Posts"
PostInterface -> PostController : getCategories()
PostController -> PostInterface : provideCategories()

alt selected Category is "Find Nearby Courts"

    User -> PostInterface: findNearbyCourts()
    PostInterface -> PostController: findNearbyCourts()

    activate CourtController
    PostController -> CourtController: findNearbyCourts()
    CourtController -> PostController: provideCourts()
    PostController -> PostInterface: provideCourts()

    User -> PostInterface: selectCourt(court)
    PostInterface -> PostController: selectCourt(court)

    PostController -> CourtController: selectCourtDetails(court)
    CourtController -> PostController: provideCourtDetails()

    PostController -> PostInterface: provideCourtDetails()
    deactivate CourtController

else if selected Category is "Badminton-Related Info"

    User -> PostInterface: getPosts()
    PostInterface -> PostController: getPosts()
    PostController -> PostInterface: providePosts()

    User -> PostInterface: selectPost(post)
    PostInterface -> PostController: selectPost(post)
    PostController -> PostInterface: providePostDetails()

else if selected Category is "Find a Courtmate"

    User -> PostInterface: joinRally()
    PostInterface -> PostController: joinRally()

    activate RallyController
    PostController -> RallyController: joinRally(user)
    RallyController -> PostController: outputFullOrNot(status)

    alt rally is not full
        PostController -> RallyController: insertUserToRally()
        RallyController -> PostController: displaySuccessMessage()
        PostController -> PostInterface: displaySuccessMessage()
    else
        RallyController -> PostController: displayErrorMessage()
        PostController -> PostInterface: displayErrorMessage()
    end

    deactivate RallyController

else if selected Category is "Sport Equipment"

    User -> PostInterface: getPosts()
    PostInterface -> PostController: getPosts()
    PostController -> PostInterface: providePosts()

    User -> PostInterface: selectPost(post)
    PostInterface -> PostController: selectPost(post)
    PostController -> PostInterface: providePostDetails()
end

deactivate PostInterface
deactivate PostController

@enduml