@startuml
title Sequence Diagram of View Info

actor User

activate PostController
User -> PostController : getCategories()
PostController -> User : provideCategories()

alt selected Category is "Find Nearby Courts"

    User -> PostController: findNearbyCourts()

    activate CourtController
    PostController -> CourtController: findNearbyCourts()
    CourtController -> PostController: provideCourts()

    PostController -> User: provideCourts()
    User -> PostController: selectCourt(court)

    PostController -> CourtController: selectCourtDetails(court)
    CourtController -> PostController: provideCourtDetails()

    PostController -> User: provideCourtDetails()
    deactivate CourtController

else if selected Category is "Badminton-Related Info"

    User -> PostController: getPosts()
    PostController -> User: providePosts()

    User -> PostController: selectPost(post)
    PostController -> User: providePostDetails()

else if selected Category is "Find a Courtmate"

    User -> PostController: joinRally()

    activate RallyController
    PostController -> RallyController: joinRally(user)
    RallyController -> PostController: outputFullOrNot(status)

    alt rally is not full
        PostController -> RallyController: insertUserToRally()
        RallyController -> PostController: displaySuccessMessage()
        PostController -> User: displaySuccessMessage()
    else
        RallyController -> PostController: displayErrorMessage()
        PostController -> User: displayErrorMessage()
    end

    deactivate RallyController

else if selected Category is "Sport Equipment"

    User -> PostController: getPosts()
    PostController -> User: providePosts()

    User -> PostController: selectPost(post)
    PostController -> User: providePostDetails()
end

deactivate PostController

@enduml