@startuml
title Sequence Diagram of Admin Management

actor Admin

participant "AdminController" as System
participant "UserController" as UC
participant "PostController" as PC

activate System

Admin -> System: click "Management dashboard"
System -> Admin: displayOptions()
Admin -> System: select an option

alt select "manage users"

    activate UC
    System -> UC: getUsers()
    UC -> System: provideUsers()

    System -> Admin: showUsers()
    Admin -> System: edit user information

    System -> UC: editUsers()
    UC -> System: displaySuccessMessage()
    deactivate UC

else select "manage posts"

    activate PC
    System -> PC: getPosts()
    PC -> System: providePosts()

    System -> Admin: showPosts()
    Admin -> System: edit post content

    System -> PC: editPost()
    PC -> System: displaySuccessMessage()
    deactivate PC

else selected option is not recognized

    System -> Admin: displayErrorMessage()

end

deactivate System

Admin -> System: log out

@enduml
