@startuml
title Sequence Diagram of Comment

actor User

activate CommentController

User -> CommentController: getPost()

activate PostController
CommentController -> PostController: getPost()
PostController -> CommentController: providePost()
deactivate PostController

CommentController -> User: showPost()

User -> CommentController: postComment()
CommentController -> User:displaySuccessMessage()


@enduml
