@startuml
title Sequence Diagram of Comment

actor User
participant "Comment Page" as System

activate System
activate Database

User -> System: open a post

System -> Database: getPost()
Database -> System: providePost()
System -> User: showPost()

User -> System: comment on the post
System -> Database: postComment()
Database -> System: displaySuccessMessage()
System -> User:displaySuccessMessage()

deactivate Database
deactivate System

@enduml
