@startuml
title Sequence Diagram of Post info

actor User

activate PostController
User -> PostController : getCategories()
PostController -> User : provideCategories()

alt Post about Badminton-Related Info

    User -[hidden]>
    User -> PostController : addPost()
    PostController -> User : displaySuccessMessage()

else Post about Find a Courtmate

    User -> PostController : createRally()

    activate RallyController
    PostController -> RallyController : createRally()
    RallyController -> PostController : showForm()
    User -> PostController : submitForm()
    PostController -> RallyController : submitForm()
    deactivate RallyController

    alt Form is not valid

        User -[hidden]>
        activate RallyController
        RallyController -> PostController : displayErrorMessage()
        PostController -> User : displayErrorMessage()
        RallyController -> PostController : showForm()
        PostController -> User : showForm()

    else Form is valid

        RallyController -> PostController : displaySuccessMessage()
        PostController -> User : displaySuccessMessage()
        deactivate RallyController

        User -[hidden]> PostController
        User -> PostController : addPost()
        PostController -> User : displaySuccessMessage()

    end

else Post about Sport Equipment

    User -[hidden]>
    activate PostController
    User -> PostController : addPost()
    PostController -> User : displaySuccessMessage()

end

deactivate PostController

@enduml
