@startuml
title Sequence Diagram of Post info

actor User

participant "Post Infomation Page" as System

activate System
activate Database

User -> System : click "Post Info"

System -> Database : getCategories()
Database -> System : provideCategories()

System -> User : showCategories()

User -> System : selectCategory()

alt Post about Badminton-Related Info

  System -> User : enter post details
  User -> System : click "submit"

  System -> Database : createPost()
  Database -> System : displaySuccessMessage()

  System -> User : displaySuccessMessage()

else Post about Find a Courtmate

  User -> System : click "Create a Rally"
  System -> User : showForm()
  User -> System : fill out the form

  alt Form is valid

      System -> Database : createPost()
      Database -> System : displaySuccessMessage()

      System -> User : displaySuccessMessage()

  else Form is not valid

    System -> User : displayErrorMessage()
    System -> User : showForm()

  end

else Post about Sport Equipment

  System -> User : enter sport equipment details
  User -> System : click "submit"

  System -> Database : createPost()
  Database -> System : displaySuccessMessage()

  System -> User : displaySuccessMessage()

end

deactivate Database
deactivate System

User -> System : logout()

@enduml
