@startuml
title Sequence Diagram of Login/Register

actor User
participant "register & login" as System
participant Database

activate Database
activate System

User -> System: click "login"

alt if it is new user
    User -> System: register()
    System -> User: showRegistrationForm()
    User -> System: username & password

    System -> Database: createUser()
    Database -> System: displaySuccessMessage()
    System -> User: displaySuccessMessage()
else if it is not new user
    User -> System: login()
    System -> User: showLoginForm()
    User -> System: username & password

    System -> Database: checkUser()
    Database -> System: yes or no

    System -> User: redirect()
end

deactivate Database
deactivate System

@enduml
